AWSTemplateFormatVersion: '2010-09-09'
Description: '[DEV] Order service - Lambda, DynamoDB, SQS, REST API Gateway'

Resources:

  ### DynamoDB Table for Orders ###
  OrdersTableDev:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: OrdersTableDev
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  ### DynamoDB Table for Idempotency ###
  IdempotencyTableDev:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: IdempotencyTableDev
      AttributeDefinitions:
        - AttributeName: idempotencyKey
          AttributeType: S
      KeySchema:
        - AttributeName: idempotencyKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true

  ### Dead Letter Queues ###
  OrderPlacedDLQDev:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OrderPlacedDLQDev

  PaymentSuccessDLQDev:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PaymentSuccessDLQDev

  ### SQS Queue for Order Events ###
  OrderPlacedQueueDev:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: OrderPlacedQueueDev
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrderPlacedDLQDev.Arn
        maxReceiveCount: 3

  ### SQS Queue for Payment Success Events ###
  PaymentSuccessQueueDev:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PaymentSuccessQueueDev
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PaymentSuccessDLQDev.Arn
        maxReceiveCount: 3

  ### CloudWatch Alarms for DLQs ###
  OrderPlacedDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cloudcart-OrderPlacedDLQ-MessagesVisible
      AlarmDescription: Alert when messages appear in OrderPlacedDLQ
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt OrderPlacedDLQDev.QueueName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  PaymentSuccessDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: cloudcart-PaymentSuccessDLQ-MessagesVisible
      AlarmDescription: Alert when messages appear in PaymentSuccessDLQ
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt PaymentSuccessDLQDev.QueueName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

  ### IAM Role for Order Lambdas ###
  OrderLambdaRoleDev:
    Type: AWS::IAM::Role
    Properties:
      RoleName: OrderLambdaRoleDev
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: OrderDynamoSQSAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                  - dynamodb:Query
                Resource:
                  - !GetAtt OrdersTableDev.Arn
                  - !Sub "${OrdersTableDev.Arn}/index/*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                Resource: !GetAtt IdempotencyTableDev.Arn
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !GetAtt OrderPlacedQueueDev.Arn

  ### Lambda Functions ###
  PlaceOrderFunctionDev:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: PlaceOrderFunctionDev
      Runtime: java21
      Handler: com.cloudcart.order.handler.PlaceOrderHandler::handleRequest
      Role: !GetAtt OrderLambdaRoleDev.Arn
      Code:
        S3Bucket: sid-mysourcecode
        S3Key: order-service-1.0.0.jar
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTableDev
          ORDER_QUEUE_URL: !Ref OrderPlacedQueueDev
          PRODUCTS_API_URL: !ImportValue cloudcart-products-ProductApiInternalUrl
          IDEMPOTENCY_TABLE: !Ref IdempotencyTableDev
          AWS_ENDPOINT_URL: http://host.docker.internal:4566

  GetOrderFunctionDev:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GetOrderFunctionDev
      Runtime: java21
      Handler: com.cloudcart.order.handler.GetOrderHandler::handleRequest
      Role: !GetAtt OrderLambdaRoleDev.Arn
      Code:
        S3Bucket: sid-mysourcecode
        S3Key: order-service-1.0.0.jar
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTableDev
          ORDER_QUEUE_URL: !Ref OrderPlacedQueueDev
          AWS_ENDPOINT_URL: http://host.docker.internal:4566

  ListOrdersFunctionDev:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ListOrdersFunctionDev
      Runtime: java21
      Handler: com.cloudcart.order.handler.ListOrdersHandler::handleRequest
      Role: !GetAtt OrderLambdaRoleDev.Arn
      Code:
        S3Bucket: sid-mysourcecode
        S3Key: order-service-1.0.0.jar
      Timeout: 15
      MemorySize: 256
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTableDev
          ORDER_QUEUE_URL: !Ref OrderPlacedQueueDev
          AWS_ENDPOINT_URL: http://host.docker.internal:4566

  ### Lambda Permissions for API Gateway ###
  PlaceOrderInvokePermissionDev:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PlaceOrderFunctionDev
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderApiDev}/*/*

  GetOrderInvokePermissionDev:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetOrderFunctionDev
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderApiDev}/*/*

  ListOrdersInvokePermissionDev:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ListOrdersFunctionDev
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${OrderApiDev}/*/*

  ### REST API ###
  OrderApiDev:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: OrderApiDev

  ### Resource: /orders ###
  OrdersResourceDev:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OrderApiDev
      ParentId: !GetAtt OrderApiDev.RootResourceId
      PathPart: orders

  ### Resource: /orders/{orderId} ###
  OrderByIdResourceDev:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref OrderApiDev
      ParentId: !Ref OrdersResourceDev
      PathPart: "{orderId}"

  ### Methods ###
  PostOrderMethodDev:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderApiDev
      ResourceId: !Ref OrdersResourceDev
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PlaceOrderFunctionDev.Arn}/invocations

  GetOrderMethodDev:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderApiDev
      ResourceId: !Ref OrderByIdResourceDev
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetOrderFunctionDev.Arn}/invocations

  ListOrdersMethodDev:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref OrderApiDev
      ResourceId: !Ref OrdersResourceDev
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListOrdersFunctionDev.Arn}/invocations

  ### Deployment & Stage ###
  OrderApiDeploymentDev:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostOrderMethodDev
      - GetOrderMethodDev
      - ListOrdersMethodDev
    Properties:
      RestApiId: !Ref OrderApiDev

  OrderApiStageDev:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref OrderApiDev
      DeploymentId: !Ref OrderApiDeploymentDev
      StageName: dev

  ### API Key Auth ###
  OrderApiKeyDev:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: OrderApiKeyDev
      Value: cloudcart-dev-key-2024
      Enabled: true

  OrderUsagePlanDev:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: OrderApiStageDev
    Properties:
      UsagePlanName: OrderUsagePlanDev
      ApiStages:
        - ApiId: !Ref OrderApiDev
          Stage: dev

  OrderUsagePlanKeyDev:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref OrderApiKeyDev
      KeyType: API_KEY
      UsagePlanId: !Ref OrderUsagePlanDev

Outputs:

  OrderQueueArn:
    Description: "ARN of the order placed SQS queue"
    Value: !GetAtt OrderPlacedQueueDev.Arn
    Export:
      Name: cloudcart-order-OrderQueueArn

  OrderQueueUrl:
    Description: "URL of the order placed SQS queue"
    Value: !Ref OrderPlacedQueueDev
    Export:
      Name: cloudcart-order-OrderQueueUrl

  OrderPlacedDLQArn:
    Description: "ARN of the OrderPlaced dead letter queue"
    Value: !GetAtt OrderPlacedDLQDev.Arn
    Export:
      Name: cloudcart-order-OrderPlacedDLQArn

  PaymentSuccessQueueArn:
    Description: "ARN of the payment success SQS queue"
    Value: !GetAtt PaymentSuccessQueueDev.Arn
    Export:
      Name: cloudcart-order-PaymentSuccessQueueArn

  PaymentSuccessQueueUrl:
    Description: "URL of the payment success SQS queue"
    Value: !Ref PaymentSuccessQueueDev
    Export:
      Name: cloudcart-order-PaymentSuccessQueueUrl

  PaymentSuccessDLQArn:
    Description: "ARN of the PaymentSuccess dead letter queue"
    Value: !GetAtt PaymentSuccessDLQDev.Arn
    Export:
      Name: cloudcart-order-PaymentSuccessDLQArn

  OrdersTableName:
    Description: "DynamoDB table name for orders"
    Value: !Ref OrdersTableDev
    Export:
      Name: cloudcart-order-OrdersTableName

  OrderApiEndpoint:
    Description: "[DEV] Order API base URL"
    Value: !Sub "https://${OrderApiDev}.execute-api.${AWS::Region}.amazonaws.com/dev"

  PlaceOrderFunctionArn:
    Value: !GetAtt PlaceOrderFunctionDev.Arn
    Export:
      Name: cloudcart-order-PlaceOrderFunctionArn

  GetOrderFunctionArn:
    Value: !GetAtt GetOrderFunctionDev.Arn
    Export:
      Name: cloudcart-order-GetOrderFunctionArn

  ListOrdersFunctionArn:
    Value: !GetAtt ListOrdersFunctionDev.Arn
    Export:
      Name: cloudcart-order-ListOrdersFunctionArn

  OrderApiKeyId:
    Value: !Ref OrderApiKeyDev
    Export:
      Name: cloudcart-order-OrderApiKeyId
